name: firebase_auth_demo
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  bloc: ^8.1.0
  carousel_slider: ^4.1.1
  cloud_firestore: ^4.3.0
  connectivity_plus: ^3.0.2
  dartz: ^0.10.1
  device_info_plus: ^7.0.1
  dio: ^4.0.6
  dotted_line: ^3.1.0
  equatable: ^2.0.5
  expandable: any
  expandable_page_view: ^1.0.17
  file_picker: ^5.2.1
  firebase_core_platform_interface: ^5.0.0
  firebase_auth_platform_interface: ^7.0.9
  firebase_auth: ^4.2.3
  firebase_core: ^2.4.0
  fl_chart: ^0.55.2
  flash: ^2.0.3+3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_html: any
  flutter_launcher_icons: any
  flutter_randomcolor: ^1.0.14
  flutter_secure_storage: any
  flutter_widget_from_html: any
  fresh_dio: ^0.3.2
  get_it: ^7.2.0
  image_picker: ^0.8.6
  injectable: ^2.1.0
  jwt_decoder: ^2.0.1
  logger: ^1.1.0
  oktoast: any
  path: ^1.8.2
  percent_indicator: ^4.2.2
  permission_handler: 10.2.0
  pin_code_fields: ^7.4.0
  provider: ^6.0.3
  rxdart: ^0.27.5
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  sliding_up_panel: ^2.0.0+1
  sprintf: ^7.0.0
  google_sign_in: any

dev_dependencies:
  build_runner: ^2.2.1
  change_app_package_name: ^1.1.0
  flutter_lints: ^1.0.0
  flutter_native_splash: any
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.3
  youtube_player_flutter: ^8.1.2


flutter:


  uses-material-design: true
